<a href="https://colab.research.google.com/github/MEY1337/deep-learning-practice/blob/main/04_multi_layer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초 실습

## List to Numpy Array

In [4]:
import numpy as np

In [5]:
test = np.array([[1,2,3], [4,5,6]])
test

array([[1, 2, 3],
       [4, 5, 6]])

### 문제1 : 아래 list 3개를 각각 행으로 갖는 배열을 생성하는 코드를 완성하고 배열의 크기를 print 하세요

In [6]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
list3 = [9,10,11,12]

arr = np.array([list1, list2, list3])

print(arr)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


## Reshape

In [7]:
arr16 = np.array(list(range(16))).reshape((4,4))
arr16

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 문제2 : 0부터 15까지의 숫자를 원소로 갖는 배열을 아래의 형태로 만드는 코드를 작성해보세요

In [8]:
# [[ 0,  1],
# [ 2,  3],
# [ 4,  5],
# [ 6,  7],
# [ 8,  9],
# [10, 11],
# [12, 13],
# [14, 15]]

arr16_reshaped = np.array(list(range(16))).reshape((8,2))
print(arr16_reshaped)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


## 0 or 1 값 채우기

In [9]:
filled_one = np.ones(16)
filled_one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
filled_zero = np.zeros((2,5))
filled_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
filled_like_arr16 = np.ones_like(arr16)
filled_like_arr16

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 문제 3 : 아래 형태를 갖는 배열을 만드는 코드를 작성해보세요
- ones, zeros, reshape 사용
- 성공했으면 concatenate의 axis를 0으로 바꿔보고 어떤 동작을 하는지 적어보세요

In [12]:
# arr_with_one 배열 참고
# [[1., 1.],
# [1., 1.],
# [1., 1.],
# [1., 1.]]

# arr_with_zero 배열 참고
# [[0., 0.],
# [0., 0.],
# [0., 0.],
# [0., 0.]]

# arr_with_one_zero 배열 참고
# [[1., 1., 0., 0.],
# [1., 1., 0., 0.],
# [1., 1., 0., 0.],
# [1., 1., 0., 0.]]

arr_with_one = np.ones((4,2))
arr_with_zero = np.zeros((4,2))

arr_with_one_zero = np.concatenate((arr_with_one, arr_with_zero), axis=1)
arr_with_one_zero
arr_with_one_zero = np.concatenate((arr_with_one, arr_with_zero), axis=1) # 수평으로 배열 합치기
arr_with_one_zero

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

## Broadcasting

In [13]:
bc = np.ones(25).reshape((5,5))
bc = bc * 5 - 1
bc

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [14]:
bc2 = bc * 0 + 3
bc + bc2

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [15]:
one_dim_arr = [5, 5, 5, 5, 5]
new_bc = bc + one_dim_arr
new_bc

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

## Slicing

In [16]:
print(arr16)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [17]:
arr16[2]

array([ 8,  9, 10, 11])

In [18]:
arr16[2,:]

array([ 8,  9, 10, 11])

In [19]:
arr16[:,2]

array([ 2,  6, 10, 14])

In [20]:
print(arr16[0:2])
print(arr16[0,2])

[[0 1 2 3]
 [4 5 6 7]]
2


In [21]:
arr16[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
arr16[arr16[:,0]<5]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### 문제 4 : 3번째 열에서(index=2) 10보다 크거나 같은 원소가 있는 행 전체를 담는 배열을 생성해보세요

In [23]:
# 결과
# [ 8,  9, 10, 11],
# [12, 13, 14, 15]]

test_arr = arr16[arr16[:,2] >= 10]
test_arr

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 평균(mean)

In [24]:
target = np.ones((10000,100))
target.shape

(10000, 100)

In [25]:
mean = target.mean(axis=0)
print(mean.shape)
print(mean)

(100,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [26]:
mean = target.mean(axis=1)
print(mean.shape)
print(mean)

(10000,)
[1. 1. 1. ... 1. 1. 1.]


# 코드를 통해서 XOR 문제 해결하기

In [27]:
# 가중치와 바이어스
w11 = np.array([-2, -2])
w12 = np.array([2, 2])
w2 = np.array([1, 1])

b1 = 3
b2 = -1
b3 = -1

In [28]:
# 퍼셉트론
def MLP(x, w, b):
    y = np.sum(w * x) + b

    if y <= 0:
        return 0
    else:
        return 1

In [29]:
# NAND 게이트
def NAND(x1,x2):
    return MLP(np.array([x1, x2]), w11, b1)

# OR 게이트
def OR(x1,x2):
    return MLP(np.array([x1, x2]), w12, b2)

# AND 게이트
def AND(x1,x2):
    return MLP(np.array([x1, x2]), w2, b3)

# XOR 게이트
def XOR(x1,x2):
    return AND(NAND(x1, x2),OR(x1,x2))

In [30]:
# x1, x2 값을 번갈아 대입해 가며 최종 값 출력
for x in [(0, 0), (1, 0), (0, 1), (1, 1)]:
    y = XOR(x[0], x[1])
    print("입력 값: " + str(x) + " 출력 값: " + str(y))

입력 값: (0, 0) 출력 값: 0
입력 값: (1, 0) 출력 값: 1
입력 값: (0, 1) 출력 값: 1
입력 값: (1, 1) 출력 값: 0


# Multi Perceptron Class 생성을 통해 해결하기

In [31]:
# XOR 문제를 해결하기 위한 다층 퍼셉트론
class SimpleMLP:
    def __init__(self):
        # 수동으로 설정한 가중치와 바이어스
        self.weights_input_hidden = np.array([[-2, 2], [-2, 2]])  # x1, x2 -> n1, n2 계산을 위한 가중치 배열
        self.bias_hidden = np.array([3, -1])  # x1, x2 -> n1, n2

        # 출력층: 1개의 뉴런
        self.weights_hidden_output = np.array([1, 1])  # n1, n2 -> y 가중치
        self.bias_output = -1  # n1, n2 -> y 바이어스

    def forward(self, X):
        # 은닉층 계산
        hidden_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
        hidden_output = np.where(hidden_input <= 0, 0, 1)
        print(f"hidden_output : {hidden_input}")

        # 출력층 계산
        final_input = np.dot(hidden_output, self.weights_hidden_output) + self.bias_output
        final_output = np.where(final_input <= 0, 0, 1)
        print(f"final_output : {final_input}")

        return final_output

In [32]:
# XOR 데이터셋 정의
XOR_X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # 입력값
XOR_y = np.array([0, 1, 1, 0])  # XOR 출력값

In [33]:
# 모델 초기화
mlp = SimpleMLP()

In [34]:
# 예측
predictions = mlp.forward(XOR_X)
# 결과 출력
print(f"XOR 문제 예측 결과: {predictions}")

hidden_output : [[ 3 -1]
 [ 1  1]
 [ 1  1]
 [-1  3]]
final_output : [0 1 1 0]
XOR 문제 예측 결과: [0 1 1 0]


# Perceptron을 이용한 NAND Gate와 OR Gate 구현

퍼셉트론의 출력식은 다음과 같다.

$$
y =
\begin{cases}
1, & w_1 x_1 + w_2 x_2 + b > 0 \
0, & \text{otherwise}
\end{cases}
$$

또한 내부 계산값은 다음과 같이 정의된다.

$$
z = w_1 x_1 + w_2 x_2 + b
$$

퍼셉트론의 입력은 다음과 같은 열 벡터 형태로 표현할 수 있다.

$$
\mathbf{x} =
\begin{bmatrix}
x_1 \
x_2
\end{bmatrix}
$$

가중치 또한 열 벡터로 표현된다.

$$
\mathbf{w} =
\begin{bmatrix}
w_1 \
w_2
\end{bmatrix}
$$

따라서 퍼셉트론의 연산은 벡터의 내적 형태로 다음과 같이 나타낼 수 있다.

$$
z = \mathbf{w}^T \mathbf{x} + b
$$

이때 출력값을 결정하는 함수는 활성화 함수이며, 퍼셉트론에서는 계단 함수(step function)를 사용한다.

$$
\phi(z) =
\begin{cases}
1, & z > 0 \
0, & z \leq 0
\end{cases}
$$

## 1. NAND Gate

NAND Gate의 진리표는 다음과 같다.

$$
(0,0) \rightarrow 1,\quad
(0,1) \rightarrow 1,\quad
(1,0) \rightarrow 1,\quad
(1,1) \rightarrow 0
$$

NAND Gate의 가중치는 열 벡터 형태로 다음과 같이 표현할 수 있다.

$$
\mathbf{w} =
\begin{bmatrix}
-2 \
-2
\end{bmatrix}
$$

따라서 다음과 같은 부등식을 만족해야 한다.

$$
b > 0
$$

$$
-2x_2 + b > 0
$$

$$
-2x_1 + b > 0
$$

$$
-2x_1 - 2x_2 + b \leq 0
$$

위 조건을 만족하는 하나의 해는 다음과 같다.

$$
b = 3
$$

이를 검증하면 다음과 같다.

$$
(0,0):\quad 0 + 0 + 3 = 3 > 0
$$

$$
(0,1):\quad 0 - 2 + 3 = 1 > 0
$$

$$
(1,0):\quad -2 + 0 + 3 = 1 > 0
$$

$$
(1,1):\quad -2 - 2 + 3 = -1 \leq 0
$$

따라서 위 가중치는 NAND Gate를 만족한다.

## 2. OR Gate

OR Gate의 진리표는 다음과 같다.

$$
(0,0) \rightarrow 0,\quad
(0,1) \rightarrow 1,\quad
(1,0) \rightarrow 1,\quad
(1,1) \rightarrow 1
$$

OR Gate의 가중치는 열 벡터 형태로 다음과 같이 표현할 수 있다.

$$
\mathbf{w} =
\begin{bmatrix}
2 \
2
\end{bmatrix}
$$

따라서 다음과 같은 부등식을 만족해야 한다.

$$
b \leq 0
$$

$$
2x_2 + b > 0
$$

$$
2x_1 + b > 0
$$

$$
2x_1 + 2x_2 + b > 0
$$

위 조건을 만족하는 하나의 해는 다음과 같다.

$$
b = -1
$$

이를 검증하면 다음과 같다.

$$
(0,0):\quad 0 + 0 - 1 = -1 \leq 0
$$

$$
(0,1):\quad 0 + 2 - 1 = 1 > 0
$$

$$
(1,0):\quad 2 + 0 - 1 = 1 > 0
$$

$$
(1,1):\quad 2 + 2 - 1 = 3 > 0
$$

따라서 위 가중치는 OR Gate를 만족한다.

## 3. 다층 퍼셉트론

다층 퍼셉트론은 입력층, 은닉층, 출력층으로 구성된 신경망 구조이다. 단층 퍼셉트론과 달리 여러 층을 통해 복잡한 패턴을 학습할 수 있으며, 각 층에서 활성화 함수를 사용하여 비선형성을 추가한다. 이러한 구조를 통해 딥러닝은 단순한 선형 분류를 넘어 복잡한 문제를 해결할 수 있다.

## 3.1 딥러닝에서 중요한 요소

딥러닝에서 중요한 요소 중 하나는 활성화 함수이다. 활성화 함수는 뉴런의 출력값을 결정하며, 비선형성을 추가하여 모델이 복잡한 패턴을 학습할 수 있도록 한다. 만약 활성화 함수가 없다면 모델은 단순한 선형 변환만 수행하게 되어 표현력이 제한된다.

## 3.2 딥러닝과 기존 머신러닝의 차이

딥러닝은 기존 머신러닝과 달리 특징을 사람이 직접 추출하지 않고, 신경망이 자동으로 학습한다는 점에서 차이가 있다. 또한 활성화 함수를 활용하여 비선형적인 문제를 효과적으로 해결할 수 있다.
